Extend the mechanism for finding config and extend it to the eslint config
ottofeller/eslint-config-ottofeller pull request #61
Opened 2022-11-13 08:29 UTC by quesabe

The prettier config utilises a mechanism for finding the config in two folders. The eslint formatting config needs to be found the same way, otherwise the config path resolution fails when ofmt is installed in a project.

Closes PLA-137.

2022-11-14 20:53 UTC, gvidon requested changes

2022-11-14 20:53 UTC, gvidon commented on eslint-config-ofmt/package.json
> +    "typescript": "4.7.4"
@quesabe why not 4.8?

2022-11-16 06:17 UTC, quesabe commented on eslint-config-ofmt/package.json
> +    "typescript": "4.7.4"
Not sure why I chose this one 😳. Maybe just the same as in the `templates` repo. Let's update is to `4.8.4` (from npm page it looks like the most popular and the most recent one from the 4.8 family).

2022-11-16 08:41 UTC, gvidon approved these changes

2022-11-16 08:42 UTC, merged