Join ofmt inputs with space
ottofeller/eslint-config-ottofeller pull request #62
Opened 2022-11-14 18:10 UTC by quesabe

Default joining with comma results in invalid patterns for prettier and eslint. On the other hand the space-separated list allows multiple inputs to be used in a single call to the ofmt executable.

Closes PLA-156.

2022-11-14 20:14 UTC, gvidon requested changes

2022-11-14 20:14 UTC, gvidon commented on ofmt/bin/ofmt.js
> +  const checkPaths = args.input.join(' ')
Is it safe to join using space? macOS escapes a space using a slash. Will this be recognised by prettier?
<img width="370" alt="image" src="https://user-images.githubusercontent.com/58164/201756473-972771f6-118b-4a7a-a8ac-ac378939a968.png">

2022-11-16 06:09 UTC, quesabe commented on ofmt/bin/ofmt.js
> +  const checkPaths = args.input.join(' ')
Depends on what we consider as safe.

If it's just a matter of ability to interpret and run, then yes - all the OS-related stuff is handled by Node. Through manual testing I have not found any issues with it.

If it's the matter of security, then no - looks like it allows arbitrary code execution. BTW I'm not sure if we are protected the way it currently is, but anyway this change seems to make it worse.

I've realised that multiple folders can be input if the input is wrapper with quotes. Thus it's not necessary to proceed with this PR.

Please let me know if we need any actions to estimate potential vulnerability or we're just good closing this issue.

2022-11-16 08:46 UTC, gvidon commented on ofmt/bin/ofmt.js
> +  const checkPaths = args.input.join(' ')
> looks like it allows arbitrary code execution

@quesabe sorry, not sure I understand how it works. Can you please give an example?

2022-11-17 17:34 UTC, quesabe commented on ofmt/bin/ofmt.js
> +  const checkPaths = args.input.join(' ')
From this branch you can enter the ofmt folder and run this command:
```shell
node bin/ofmt.js --lint "bin/olint.js; echo This is the unexpected execution"
```
to get this output:
```shell
Checking formatting...
All matched files use Prettier code style!
This is the unexpected execution

This is the unexpected execution
```

However I've checked the `master` branch and can confirm that it has the same behaviour.

2022-11-20 14:58 UTC, gvidon commented on ofmt/bin/ofmt.js
> +  const checkPaths = args.input.join(' ')
Ok, let's skip this for now. Looks like not a major issue to me.

2022-11-20 14:59 UTC, gvidon approved these changes
@quesabe please fix the conflicts and feel free merging the PR.

2022-11-22 17:28 UTC, quesabe commented
>

2022-11-22 17:32 UTC, quesabe commented
> @quesabe please fix the conflicts and feel free merging the PR.

After some consideration and finding a way to have multiple inputs without this fix (just wrapping arguments with quotes), I think that this PR is not necessary to merge - it does not provide that much advantage. What do you think? I'd vote for closing it without merging.

2022-11-24 19:21 UTC, gvidon commented
@quesabe yeah, let's close it then.

2022-11-24 19:21 UTC, closed without merging